version: '3.9'

volumes:
  database-data:
    name: data-postgres

networks:
  mynetwork:
      name: ${APP_NETWORK}

services:
  postgresql:
    container_name: postgresql-srv
    image: postgres:alpine3.17
    env_file:
      - postgresql.env
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - pgadmin.env
      - .env
    ports: 
      - "5050:80"
    networks:
      - mynetwork