version: '3.9'

networks:
  mynetwork:
    name: ${APP_NETWORK}

services:
  msvc-courses:
    container_name: ${SRV_COURSES}
    #build:
    #  context: ../
    #  dockerfile: ./ms-courses/Dockerfile
    image: jaefallac/cursos
    env_file:
      - .env
      - courses.env
    ports:
      - ${COURSES_PORT}:${COURSES_PORT}
    networks:
      - mynetwork
    depends_on:
      - postgresql
    restart: always
