version: '3.9'

networks:
  mynetwork:
    name: ${APP_NETWORK}

services:
  msvc-users:
    container_name: ${SRV_USERS}
    #build:
    #  context: ../
    #  dockerfile: ./ms-users/Dockerfile
    image: jaefallac/usuarios
    env_file:
      - .env
      - users.env
    ports:
      - ${USERS_PORT}:${USERS_PORT}
    networks:
      - mynetwork
    restart: always
    depends_on:
      - mariadb
