version: '3.9'

volumes:
  mariadb:
    name: data-mysql

networks:
  mynetwork:
      name: ${APP_NETWORK}

services:

  mariadb:
    container_name: mysql-srv
    image: mariadb:latest
    env_file:
      - .env
      - mysql.env
    ports:
        - "3306:3306"
    volumes:
     - mariadb:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    container_name: myadmin
    image: phpmyadmin
    restart: always
    env_file:
      - .env
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306 
    networks:
      - mynetwork