version: '3.9'

volumes:
  mariadb:
    name: data-mysql

networks:
  mynetwork:
      name: ${APP_NETWORK}

services:

  mariadb:
    container_name: mysql-srv
    image: mariadb:latest
    env_file:
      - .env
      - mysql.env
    ports:
        - "3306:3306"
    volumes:
     - mariadb:/var/lib/mysql
    networks:
      - mynetwork